# Generated by Django 3.1.3 on 2020-11-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
